# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-11 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subcategories', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quiz_SubCategories',
            new_name='ProgrammingSubCategories',
        ),
        migrations.RenameModel(
            old_name='Programming_SubCategories',
            new_name='QuizSubCategories',
        ),
        migrations.RenameModel(
            old_name='Verbal_SubCategories',
            new_name='VerbalSubCategories',
        ),
    ]
