# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-12 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subcategories', '0002_auto_20160911_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programmingsubcategories',
            options={'verbose_name': 'Programming', 'verbose_name_plural': 'Programming'},
        ),
        migrations.AlterModelOptions(
            name='quizsubcategories',
            options={'verbose_name': 'Quiz', 'verbose_name_plural': 'Quiz'},
        ),
        migrations.AlterModelOptions(
            name='verbalsubcategories',
            options={'verbose_name': 'Verbal', 'verbose_name_plural': 'Verbal'},
        ),
    ]
