# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-12 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0003_programmingquestion_quizquestion_verbalquestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programmingquestion',
            options={'verbose_name': 'Programming', 'verbose_name_plural': 'Programming'},
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'verbose_name': 'Quiz', 'verbose_name_plural': 'Quiz'},
        ),
        migrations.AlterModelOptions(
            name='verbalquestion',
            options={'verbose_name': 'Verbal', 'verbose_name_plural': 'Verbal'},
        ),
        migrations.AlterField(
            model_name='programmingquestion',
            name='subCategory',
            field=models.CharField(choices=[(3, 'Arrays'), (4, 'Strings')], max_length=200),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='subCategory',
            field=models.CharField(choices=[(3, 'Time and Work'), (4, 'Profit and Loss')], max_length=200),
        ),
    ]
