# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-11 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0005_auto_20160912_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmingquestion',
            name='subCategory',
            field=models.IntegerField(choices=[(3, 'Arrays'), (4, 'Strings')]),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='subCategory',
            field=models.IntegerField(choices=[(3, 'Time and Work'), (4, 'Profit and Loss')]),
        ),
        migrations.AlterField(
            model_name='verbalquestion',
            name='subCategory',
            field=models.IntegerField(choices=[(1, 'Comprehension')]),
        ),
    ]
