# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-10 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0007_auto_20170110_1332'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
