# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-22 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20160822_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csequestion',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='ecequestion',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='eeequestion',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='itquestion',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='mechquestion',
            name='choices',
        ),
        migrations.AddField(
            model_name='csequestion',
            name='choice1',
            field=models.CharField(default='a', max_length=500),
        ),
        migrations.AddField(
            model_name='csequestion',
            name='choice2',
            field=models.CharField(default='b', max_length=500),
        ),
        migrations.AddField(
            model_name='csequestion',
            name='choice3',
            field=models.CharField(default='c', max_length=500),
        ),
        migrations.AddField(
            model_name='csequestion',
            name='choice4',
            field=models.CharField(default='d', max_length=500),
        ),
        migrations.AddField(
            model_name='ecequestion',
            name='choice1',
            field=models.CharField(default='a', max_length=500),
        ),
        migrations.AddField(
            model_name='ecequestion',
            name='choice2',
            field=models.CharField(default='b', max_length=500),
        ),
        migrations.AddField(
            model_name='ecequestion',
            name='choice3',
            field=models.CharField(default='c', max_length=500),
        ),
        migrations.AddField(
            model_name='ecequestion',
            name='choice4',
            field=models.CharField(default='d', max_length=500),
        ),
        migrations.AddField(
            model_name='eeequestion',
            name='choice1',
            field=models.CharField(default='a', max_length=500),
        ),
        migrations.AddField(
            model_name='eeequestion',
            name='choice2',
            field=models.CharField(default='b', max_length=500),
        ),
        migrations.AddField(
            model_name='eeequestion',
            name='choice3',
            field=models.CharField(default='c', max_length=500),
        ),
        migrations.AddField(
            model_name='eeequestion',
            name='choice4',
            field=models.CharField(default='d', max_length=500),
        ),
        migrations.AddField(
            model_name='itquestion',
            name='choice1',
            field=models.CharField(default='a', max_length=500),
        ),
        migrations.AddField(
            model_name='itquestion',
            name='choice2',
            field=models.CharField(default='b', max_length=500),
        ),
        migrations.AddField(
            model_name='itquestion',
            name='choice3',
            field=models.CharField(default='c', max_length=500),
        ),
        migrations.AddField(
            model_name='itquestion',
            name='choice4',
            field=models.CharField(default='d', max_length=500),
        ),
        migrations.AddField(
            model_name='mechquestion',
            name='choice1',
            field=models.CharField(default='a', max_length=500),
        ),
        migrations.AddField(
            model_name='mechquestion',
            name='choice2',
            field=models.CharField(default='b', max_length=500),
        ),
        migrations.AddField(
            model_name='mechquestion',
            name='choice3',
            field=models.CharField(default='c', max_length=500),
        ),
        migrations.AddField(
            model_name='mechquestion',
            name='choice4',
            field=models.CharField(default='d', max_length=500),
        ),
    ]
