# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-11 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestAllocation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='TestName',
            field=models.CharField(default='Test', max_length=200),
            preserve_default=False,
        ),
    ]
