# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-27 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestAllocation', '0002_quiz_testname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programming',
            name='TestName',
            field=models.CharField(default='', max_length=200),
        ),
    ]
