# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-29 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestAllocation', '0004_verbal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verbal',
            name='VerbalTagName',
            field=models.IntegerField(choices=[(1, 'Comprehension')], verbose_name='Verbal Tags'),
        ),
    ]
