# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-12 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batches',
            options={'verbose_name': 'Batch', 'verbose_name_plural': 'Batches'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
    ]
