# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-10 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('subCategory', models.IntegerField(choices=[(4, 'Syllogism'), (5, 'Arithmetic Reasoning'), (6, 'Series Completion')])),
                ('TypeofQuestion', models.IntegerField(choices=[(1, 'Programming'), (2, 'Verbal'), (3, 'Quiz')])),
            ],
        ),
    ]
