# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-10 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionDumps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='subCategory',
            field=models.IntegerField(choices=[(3, 'Time and Work'), (4, 'Profit and Loss')]),
        ),
    ]
