# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-10 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionDumps', '0002_auto_20170110_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('subCategory', models.IntegerField(choices=[(3, 'Arrays'), (4, 'Strings')])),
            ],
            options={
                'verbose_name': 'Programming',
                'verbose_name_plural': 'Programming',
            },
        ),
        migrations.CreateModel(
            name='QuizFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('subCategory', models.IntegerField(choices=[(3, 'Time and Work'), (4, 'Profit and Loss')])),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quiz',
            },
        ),
        migrations.CreateModel(
            name='VerbalFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('subCategory', models.IntegerField(choices=[(4, 'Syllogism'), (5, 'Arithmetic Reasoning'), (6, 'Series Completion')])),
            ],
            options={
                'verbose_name': 'Verbal',
                'verbose_name_plural': 'Verbal',
            },
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
