# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-11 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('testcases', models.TextField()),
                ('tags', models.CharField(max_length=200)),
            ],
        ),
    ]
