# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-19 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
