# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-19 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0002_questions_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rollno', models.CharField(max_length=6)),
                ('dept', models.CharField(max_length=6)),
                ('year', models.CharField(max_length=5)),
                ('questions_solved', models.TextField()),
                ('questions_partially_solved', models.TextField()),
                ('total_score', models.IntegerField()),
            ],
        ),
    ]
