# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-20 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0003_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rollno', models.CharField(max_length=6)),
                ('dept', models.CharField(max_length=6)),
                ('year', models.CharField(max_length=5)),
            ],
        ),
    ]
