# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-22 04:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0005_auto_20160822_0956'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CodingQuestions',
            new_name='CodingQuestion',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='questions_partially_solved',
            new_name='Question_partially_solved',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='questions_solved',
            new_name='Question_solved',
        ),
    ]
