# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-06 04:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0002_auto_20160906_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='EndDate',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 9, 6, 4, 34, 19, 500701, tzinfo=utc), verbose_name='End Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='EndTime',
            field=models.TimeField(blank=True, default=datetime.datetime(2016, 9, 6, 4, 34, 24, 402981, tzinfo=utc), verbose_name='End Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='StartDate',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 9, 6, 4, 34, 27, 327149, tzinfo=utc), verbose_name='Start Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='StartTime',
            field=models.TimeField(blank=True, default=datetime.datetime(2016, 9, 6, 4, 34, 29, 713285, tzinfo=utc), verbose_name='Start Time'),
            preserve_default=False,
        ),
    ]
