# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-06 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0004_test_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programming_SubCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='SubCategories',
            new_name='Quiz_SubCategories',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='subCategory',
        ),
        migrations.RemoveField(
            model_name='test',
            name='TagName',
        ),
        migrations.RemoveField(
            model_name='verbal',
            name='subCategory',
        ),
        migrations.AddField(
            model_name='test',
            name='Department',
            field=models.CharField(choices=[(1, 'CSE'), (2, 'CIVIL'), (3, 'EEE'), (4, 'ECE'), (5, 'IT'), (6, 'MECH')], default='cse', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='Batch',
            field=models.CharField(choices=[(1, '2013-2017'), (2, '2014-2018'), (3, '2015-2019'), (4, '2016-2020')], max_length=200),
        ),
    ]
