# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-06 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0005_auto_20160906_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='subCategory',
            field=models.CharField(choices=[(1, 'Arrays'), (2, 'Strings'), (3, 'Dynamic Programming')], default='Arrays', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='ProgrammingTagName',
            field=models.CharField(default='Arrays', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='QuizTagName',
            field=models.CharField(choices=[(1, 'Arrays'), (2, 'Strings'), (3, 'Dynamic Programming')], default='Arrays', max_length=200),
            preserve_default=False,
        ),
    ]
