# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-06 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0006_auto_20160906_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('op1', models.CharField(max_length=200, verbose_name='Option1')),
                ('op2', models.CharField(max_length=200, verbose_name='Option2')),
                ('op3', models.CharField(max_length=200, verbose_name='Option3')),
                ('op4', models.CharField(max_length=200, verbose_name='Option4')),
                ('subCategory', models.CharField(choices=[(1, 'Strings'), (2, 'Dynamic Programming'), (3, 'Arrays')], max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='quiz',
            name='op1',
            field=models.CharField(max_length=200, verbose_name='Option1'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='op2',
            field=models.CharField(max_length=200, verbose_name='Option2'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='op3',
            field=models.CharField(max_length=200, verbose_name='Option3'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='op4',
            field=models.CharField(max_length=200, verbose_name='Option4'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='subCategory',
            field=models.CharField(choices=[(4, 'Time and Work'), (5, 'Train'), (6, 'Speed and Distance'), (7, 'Profit and Loss')], max_length=200),
        ),
        migrations.AlterField(
            model_name='test',
            name='ProgrammingTagName',
            field=models.CharField(choices=[(1, 'Strings'), (2, 'Dynamic Programming'), (3, 'Arrays')], max_length=200, verbose_name='Programming Tags'),
        ),
        migrations.AlterField(
            model_name='test',
            name='QuizTagName',
            field=models.CharField(choices=[(4, 'Time and Work'), (5, 'Train'), (6, 'Speed and Distance'), (7, 'Profit and Loss')], max_length=200, verbose_name='Quiz Tags'),
        ),
        migrations.AlterField(
            model_name='verbal',
            name='op1',
            field=models.CharField(max_length=200, verbose_name='Option1'),
        ),
        migrations.AlterField(
            model_name='verbal',
            name='op2',
            field=models.CharField(max_length=200, verbose_name='Option2'),
        ),
        migrations.AlterField(
            model_name='verbal',
            name='op3',
            field=models.CharField(max_length=200, verbose_name='Option3'),
        ),
        migrations.AlterField(
            model_name='verbal',
            name='op4',
            field=models.CharField(max_length=200, verbose_name='Option4'),
        ),
    ]
