# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-06 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0007_auto_20160906_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verbal_SubCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tag Name')),
            ],
        ),
        migrations.AlterField(
            model_name='programming_subcategories',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Tag Name'),
        ),
        migrations.AlterField(
            model_name='quiz_subcategories',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Tag Name'),
        ),
    ]
