# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-06 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0008_auto_20160906_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='verbal',
            name='subCategory',
            field=models.CharField(default='Comprehension', max_length=200),
            preserve_default=False,
        ),
    ]
