# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-06 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0009_verbal_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmingquestion',
            name='op1',
        ),
        migrations.RemoveField(
            model_name='programmingquestion',
            name='op2',
        ),
        migrations.RemoveField(
            model_name='programmingquestion',
            name='op3',
        ),
        migrations.RemoveField(
            model_name='programmingquestion',
            name='op4',
        ),
        migrations.AddField(
            model_name='programmingquestion',
            name='Output',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programmingquestion',
            name='TestCases',
            field=models.CharField(default='2', max_length=200, verbose_name='Test Cases'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='Answer',
            field=models.CharField(default='3', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verbal',
            name='Answer',
            field=models.CharField(default='3', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programmingquestion',
            name='subCategory',
            field=models.CharField(choices=[(1, 'Strings'), (2, 'Dynamic Programming'), (3, 'Arrays'), (4, 'Data Structures')], max_length=200),
        ),
        migrations.AlterField(
            model_name='test',
            name='ProgrammingTagName',
            field=models.CharField(choices=[(1, 'Strings'), (2, 'Dynamic Programming'), (3, 'Arrays'), (4, 'Data Structures')], max_length=200, verbose_name='Programming Tags'),
        ),
        migrations.AlterField(
            model_name='verbal',
            name='subCategory',
            field=models.CharField(choices=[(1, 'Comprehension'), (2, 'Error Identification')], max_length=200),
        ),
    ]
