# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-06 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0010_auto_20160906_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='ProgrammingTagName',
            field=models.IntegerField(choices=[(1, 'Strings'), (2, 'Dynamic Programming'), (3, 'Arrays'), (4, 'Data Structures')], max_length=200, verbose_name='Programming Tags'),
        ),
        migrations.AlterField(
            model_name='test',
            name='QuizTagName',
            field=models.IntegerField(choices=[(4, 'Time and Work'), (5, 'Train'), (6, 'Speed and Distance'), (7, 'Profit and Loss')], max_length=200, verbose_name='Quiz Tags'),
        ),
    ]
