# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-06 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0011_auto_20160906_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='Batch',
            field=models.IntegerField(choices=[(1, '2013-2017'), (2, '2014-2018'), (3, '2015-2019'), (4, '2016-2020')], max_length=200),
        ),
        migrations.AlterField(
            model_name='test',
            name='Department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('CIVIL', 'CIVIL'), ('EEE', 'EEE'), ('ECE', 'ECE'), ('IT', 'IT'), ('MECH', 'MECH')], max_length=200),
        ),
    ]
