# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-10 04:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0013_auto_20160906_2218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Batches',
        ),
        migrations.DeleteModel(
            name='Programming_SubCategories',
        ),
        migrations.DeleteModel(
            name='ProgrammingQuestion',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='Quiz_SubCategories',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Verbal',
        ),
        migrations.DeleteModel(
            name='Verbal_SubCategories',
        ),
    ]
