# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-11 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0016_auto_20160911_1639'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProgrammingQuestion',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='Verbal',
        ),
    ]
