# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-11 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0018_programming_quiz_verbal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Batches',
        ),
    ]
