# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-11 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackerspace', '0019_delete_batches'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Programming',
        ),
        migrations.DeleteModel(
            name='Programming_SubCategories',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='Quiz_SubCategories',
        ),
        migrations.DeleteModel(
            name='Verbal',
        ),
        migrations.DeleteModel(
            name='Verbal_SubCategories',
        ),
    ]
